name: "hello-world-app"
displayName: "Hello World App"
realm: "samples"
version: 1.0.21
description: "An App that exposes an endpoint at /hello-world"

readme: |
  ## Hello World App

  This is a sample App that exposes an endpoint at [https://cluster-ip/api/samples/hello-world](https://cluster-ip/api/samples/hello-world). 
  It is used to demonstrate how to create an App using the App Definition format.

changelog: |
  ## [1.0.21] - 2026-05-15

  ### Added
  - Display name for the app.

  ## [1.0.20] - 2026-03-17

  ### Changed
  - Something important.

  ## [1.0.19] - 2026-03-16

  ### Added
  - New section in the readme file.

  ## [1.0.18] - 2026-03-14

  ### Fixed
  - Minor adjustments and performance optimizations.

  ## [1.0.17] - 2026-03-13

  ### Added
  - Added readme and changelog.

prerequisites:
  systemVersion: ">=0.3.10"

services:
- name: pub-samples-hello-world
  routes:
  - name: hello-world-route
    port: 80
    targetPort: 80
    ingress:
      rootPath: "/api/samples/hello-world"
      redirectPath: "/"
      rules:
      - path: "/"

  containers:
  - name: hello-world-container
    image: sandbox.io/hello-world:1.0.21
